[2022-06-20 01:34:22,580] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-10T00:00:00+00:00 [queued]>
[2022-06-20 01:34:22,592] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-10T00:00:00+00:00 [queued]>
[2022-06-20 01:34:22,594] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:22,596] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:34:22,598] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:22,634] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-10 00:00:00+00:00
[2022-06-20 01:34:22,651] {standard_task_runner.py:52} INFO - Started process 226 to run task
[2022-06-20 01:34:22,662] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-10T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/data-pipline-book/2_1_download_rocket_launches.py', '--cfg-path', '/tmp/tmp7mjvxh_g', '--error-file', '/tmp/tmp9ecp5kur']
[2022-06-20 01:34:22,666] {standard_task_runner.py:80} INFO - Job 40: Subtask get_pictures
[2022-06-20 01:34:22,763] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-10T00:00:00+00:00 [running]> on host b8db81cc5447
[2022-06-20 01:34:23,045] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-10T00:00:00+00:00
[2022-06-20 01:34:23,051] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data-pipline-book/2_1_download_rocket_launches.py", line 40, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:34:23,078] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220610T000000, start_date=20220620T013422, end_date=20220620T013423
[2022-06-20 01:34:23,103] {standard_task_runner.py:97} ERROR - Failed to execute job 40 for task get_pictures ('results'; 226)
[2022-06-20 01:34:23,128] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:34:23,232] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-20 01:51:13,554] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-10T00:00:00+00:00 [queued]>
[2022-06-20 01:51:13,566] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-10T00:00:00+00:00 [queued]>
[2022-06-20 01:51:13,568] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:13,571] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:51:13,572] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:13,606] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-10 00:00:00+00:00
[2022-06-20 01:51:13,614] {standard_task_runner.py:52} INFO - Started process 184 to run task
[2022-06-20 01:51:13,624] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-10T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/chapter02/dags/download_rocket_launches.py', '--cfg-path', '/tmp/tmptljk0kxr', '--error-file', '/tmp/tmphxw0p771']
[2022-06-20 01:51:13,668] {standard_task_runner.py:80} INFO - Job 24: Subtask get_pictures
[2022-06-20 01:51:13,823] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-10T00:00:00+00:00 [running]> on host b39ea3d1be4a
[2022-06-20 01:51:14,089] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-10T00:00:00+00:00
[2022-06-20 01:51:14,097] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/chapter02/dags/download_rocket_launches.py", line 32, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:51:14,134] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220610T000000, start_date=20220620T015113, end_date=20220620T015114
[2022-06-20 01:51:14,155] {standard_task_runner.py:97} ERROR - Failed to execute job 24 for task get_pictures ('results'; 184)
[2022-06-20 01:51:14,179] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:51:14,246] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
