[2022-06-20 01:34:23,655] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-14T00:00:00+00:00 [queued]>
[2022-06-20 01:34:23,689] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-14T00:00:00+00:00 [queued]>
[2022-06-20 01:34:23,693] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:23,696] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:34:23,699] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:23,733] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-14 00:00:00+00:00
[2022-06-20 01:34:23,744] {standard_task_runner.py:52} INFO - Started process 234 to run task
[2022-06-20 01:34:23,752] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-14T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/data-pipline-book/2_1_download_rocket_launches.py', '--cfg-path', '/tmp/tmplv1qbysw', '--error-file', '/tmp/tmpz04_7geg']
[2022-06-20 01:34:23,757] {standard_task_runner.py:80} INFO - Job 42: Subtask get_pictures
[2022-06-20 01:34:23,870] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-14T00:00:00+00:00 [running]> on host b8db81cc5447
[2022-06-20 01:34:24,058] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-14T00:00:00+00:00
[2022-06-20 01:34:24,062] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data-pipline-book/2_1_download_rocket_launches.py", line 40, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:34:24,078] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220614T000000, start_date=20220620T013423, end_date=20220620T013424
[2022-06-20 01:34:24,097] {standard_task_runner.py:97} ERROR - Failed to execute job 42 for task get_pictures ('results'; 234)
[2022-06-20 01:34:24,141] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:34:24,212] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-20 01:51:14,230] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-14T00:00:00+00:00 [queued]>
[2022-06-20 01:51:14,242] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-14T00:00:00+00:00 [queued]>
[2022-06-20 01:51:14,245] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:14,261] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:51:14,269] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:14,305] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-14 00:00:00+00:00
[2022-06-20 01:51:14,317] {standard_task_runner.py:52} INFO - Started process 195 to run task
[2022-06-20 01:51:14,326] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-14T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/chapter02/dags/download_rocket_launches.py', '--cfg-path', '/tmp/tmphgqqygat', '--error-file', '/tmp/tmpzuonn7sf']
[2022-06-20 01:51:14,332] {standard_task_runner.py:80} INFO - Job 25: Subtask get_pictures
[2022-06-20 01:51:14,400] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-14T00:00:00+00:00 [running]> on host b39ea3d1be4a
[2022-06-20 01:51:14,559] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-14T00:00:00+00:00
[2022-06-20 01:51:14,581] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/chapter02/dags/download_rocket_launches.py", line 32, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:51:14,612] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220614T000000, start_date=20220620T015114, end_date=20220620T015114
[2022-06-20 01:51:14,646] {standard_task_runner.py:97} ERROR - Failed to execute job 25 for task get_pictures ('results'; 195)
[2022-06-20 01:51:14,702] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:51:14,794] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
