[2022-06-20 01:34:22,299] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-09T00:00:00+00:00 [queued]>
[2022-06-20 01:34:22,311] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-09T00:00:00+00:00 [queued]>
[2022-06-20 01:34:22,314] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:22,315] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:34:22,317] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:22,363] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-09 00:00:00+00:00
[2022-06-20 01:34:22,373] {standard_task_runner.py:52} INFO - Started process 223 to run task
[2022-06-20 01:34:22,400] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-09T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/data-pipline-book/2_1_download_rocket_launches.py', '--cfg-path', '/tmp/tmp4vp9lb2k', '--error-file', '/tmp/tmpzq2pavjn']
[2022-06-20 01:34:22,405] {standard_task_runner.py:80} INFO - Job 38: Subtask get_pictures
[2022-06-20 01:34:22,510] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-09T00:00:00+00:00 [running]> on host b8db81cc5447
[2022-06-20 01:34:22,638] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-09T00:00:00+00:00
[2022-06-20 01:34:22,641] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data-pipline-book/2_1_download_rocket_launches.py", line 40, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:34:22,658] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220609T000000, start_date=20220620T013422, end_date=20220620T013422
[2022-06-20 01:34:22,696] {standard_task_runner.py:97} ERROR - Failed to execute job 38 for task get_pictures ('results'; 223)
[2022-06-20 01:34:22,721] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:34:22,798] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-20 01:51:13,490] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-09T00:00:00+00:00 [queued]>
[2022-06-20 01:51:13,521] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-09T00:00:00+00:00 [queued]>
[2022-06-20 01:51:13,522] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:13,525] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:51:13,527] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:13,563] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-09 00:00:00+00:00
[2022-06-20 01:51:13,577] {standard_task_runner.py:52} INFO - Started process 181 to run task
[2022-06-20 01:51:13,585] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-09T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/chapter02/dags/download_rocket_launches.py', '--cfg-path', '/tmp/tmp8ovwzqmk', '--error-file', '/tmp/tmp36h95wyx']
[2022-06-20 01:51:13,594] {standard_task_runner.py:80} INFO - Job 21: Subtask get_pictures
[2022-06-20 01:51:13,686] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-09T00:00:00+00:00 [running]> on host b39ea3d1be4a
[2022-06-20 01:51:13,807] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-09T00:00:00+00:00
[2022-06-20 01:51:13,815] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/chapter02/dags/download_rocket_launches.py", line 32, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:51:13,871] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220609T000000, start_date=20220620T015113, end_date=20220620T015113
[2022-06-20 01:51:13,909] {standard_task_runner.py:97} ERROR - Failed to execute job 21 for task get_pictures ('results'; 181)
[2022-06-20 01:51:13,974] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:51:14,089] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
