[2022-06-20 01:34:23,947] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-16T00:00:00+00:00 [queued]>
[2022-06-20 01:34:23,963] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-16T00:00:00+00:00 [queued]>
[2022-06-20 01:34:23,970] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:23,972] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:34:23,979] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:24,004] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-16 00:00:00+00:00
[2022-06-20 01:34:24,022] {standard_task_runner.py:52} INFO - Started process 236 to run task
[2022-06-20 01:34:24,027] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-16T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/data-pipline-book/2_1_download_rocket_launches.py', '--cfg-path', '/tmp/tmpoazv2ray', '--error-file', '/tmp/tmpg4k58ham']
[2022-06-20 01:34:24,035] {standard_task_runner.py:80} INFO - Job 45: Subtask get_pictures
[2022-06-20 01:34:24,106] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-16T00:00:00+00:00 [running]> on host b8db81cc5447
[2022-06-20 01:34:24,213] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-16T00:00:00+00:00
[2022-06-20 01:34:24,216] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data-pipline-book/2_1_download_rocket_launches.py", line 40, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:34:24,232] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220616T000000, start_date=20220620T013423, end_date=20220620T013424
[2022-06-20 01:34:24,245] {standard_task_runner.py:97} ERROR - Failed to execute job 45 for task get_pictures ('results'; 236)
[2022-06-20 01:34:24,292] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:34:24,320] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-20 01:51:14,369] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-16T00:00:00+00:00 [queued]>
[2022-06-20 01:51:14,385] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-16T00:00:00+00:00 [queued]>
[2022-06-20 01:51:14,387] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:14,392] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:51:14,396] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:14,419] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-16 00:00:00+00:00
[2022-06-20 01:51:14,431] {standard_task_runner.py:52} INFO - Started process 197 to run task
[2022-06-20 01:51:14,436] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-16T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/chapter02/dags/download_rocket_launches.py', '--cfg-path', '/tmp/tmpw_wjgn2x', '--error-file', '/tmp/tmpgpmadibr']
[2022-06-20 01:51:14,441] {standard_task_runner.py:80} INFO - Job 27: Subtask get_pictures
[2022-06-20 01:51:14,612] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-16T00:00:00+00:00 [running]> on host b39ea3d1be4a
[2022-06-20 01:51:14,768] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-16T00:00:00+00:00
[2022-06-20 01:51:14,771] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/chapter02/dags/download_rocket_launches.py", line 32, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:51:14,797] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220616T000000, start_date=20220620T015114, end_date=20220620T015114
[2022-06-20 01:51:14,820] {standard_task_runner.py:97} ERROR - Failed to execute job 27 for task get_pictures ('results'; 197)
[2022-06-20 01:51:14,868] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:51:14,920] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
