[2022-06-20 01:34:22,263] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-11T00:00:00+00:00 [queued]>
[2022-06-20 01:34:22,286] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-11T00:00:00+00:00 [queued]>
[2022-06-20 01:34:22,289] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:22,291] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:34:22,293] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:22,320] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-11 00:00:00+00:00
[2022-06-20 01:34:22,336] {standard_task_runner.py:52} INFO - Started process 221 to run task
[2022-06-20 01:34:22,352] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-11T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/data-pipline-book/2_1_download_rocket_launches.py', '--cfg-path', '/tmp/tmpunomgemc', '--error-file', '/tmp/tmpftl_cdab']
[2022-06-20 01:34:22,368] {standard_task_runner.py:80} INFO - Job 37: Subtask get_pictures
[2022-06-20 01:34:22,481] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-11T00:00:00+00:00 [running]> on host b8db81cc5447
[2022-06-20 01:34:22,632] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-11T00:00:00+00:00
[2022-06-20 01:34:22,636] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data-pipline-book/2_1_download_rocket_launches.py", line 40, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:34:22,665] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220611T000000, start_date=20220620T013422, end_date=20220620T013422
[2022-06-20 01:34:22,686] {standard_task_runner.py:97} ERROR - Failed to execute job 37 for task get_pictures ('results'; 221)
[2022-06-20 01:34:22,736] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:34:22,809] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-20 01:51:13,528] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-11T00:00:00+00:00 [queued]>
[2022-06-20 01:51:13,542] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-11T00:00:00+00:00 [queued]>
[2022-06-20 01:51:13,544] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:13,546] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:51:13,550] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:13,579] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-11 00:00:00+00:00
[2022-06-20 01:51:13,587] {standard_task_runner.py:52} INFO - Started process 183 to run task
[2022-06-20 01:51:13,594] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-11T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/chapter02/dags/download_rocket_launches.py', '--cfg-path', '/tmp/tmpa7svsxh6', '--error-file', '/tmp/tmpqh0lj_de']
[2022-06-20 01:51:13,602] {standard_task_runner.py:80} INFO - Job 23: Subtask get_pictures
[2022-06-20 01:51:13,713] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-11T00:00:00+00:00 [running]> on host b39ea3d1be4a
[2022-06-20 01:51:13,875] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-11T00:00:00+00:00
[2022-06-20 01:51:13,881] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/chapter02/dags/download_rocket_launches.py", line 32, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:51:13,912] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220611T000000, start_date=20220620T015113, end_date=20220620T015113
[2022-06-20 01:51:13,943] {standard_task_runner.py:97} ERROR - Failed to execute job 23 for task get_pictures ('results'; 183)
[2022-06-20 01:51:14,013] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:51:14,130] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
