[2022-06-14 15:04:46,228] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T13:00:00+00:00 [queued]>
[2022-06-14 15:04:46,248] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T13:00:00+00:00 [queued]>
[2022-06-14 15:04:46,251] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 15:04:46,253] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-14 15:04:46,257] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 15:04:46,295] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data> on 2022-06-14 13:00:00+00:00
[2022-06-14 15:04:46,309] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'listing_4_05', 'get_data', 'scheduled__2022-06-14T13:00:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/listing_4_5.py', '--cfg-path', '/tmp/tmpz4_wkokc', '--error-file', '/tmp/tmpmh_2_aws']
[2022-06-14 15:04:46,304] {standard_task_runner.py:52} INFO - Started process 74064 to run task
[2022-06-14 15:04:46,316] {standard_task_runner.py:80} INFO - Job 153: Subtask get_data
[2022-06-14 15:04:46,471] {task_command.py:369} INFO - Running <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T13:00:00+00:00 [running]> on host 48de8cc79e8d
[2022-06-14 15:04:46,668] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listing_4_05
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-14T13:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-14T13:00:00+00:00
[2022-06-14 15:04:46,671] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-06-14 23:26:10,427] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T13:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2022-06-14 23:26:10,432] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-14T13:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2022-06-14 23:26:10,434] {local_task_job.py:101} INFO - Task is not able to be run
[2022-06-14 23:26:10,731] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-06-14 23:26:10,739] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 74064. PIDs of all processes in the group: [74064]
[2022-06-14 23:26:10,740] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 74064
[2022-06-14 23:26:10,748] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-06-14 23:26:10,837] {process_utils.py:75} INFO - Process psutil.Process(pid=74064, status='terminated', exitcode=0, started='15:04:45') (74064) terminated with exit code 0
