[2022-06-20 01:34:25,062] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-17T00:00:00+00:00 [queued]>
[2022-06-20 01:34:25,068] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-17T00:00:00+00:00 [queued]>
[2022-06-20 01:34:25,070] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:25,071] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:34:25,071] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:25,084] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-17 00:00:00+00:00
[2022-06-20 01:34:25,089] {standard_task_runner.py:52} INFO - Started process 241 to run task
[2022-06-20 01:34:25,092] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-17T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/data-pipline-book/2_1_download_rocket_launches.py', '--cfg-path', '/tmp/tmp5mhx8fpq', '--error-file', '/tmp/tmpnb9_1n0b']
[2022-06-20 01:34:25,094] {standard_task_runner.py:80} INFO - Job 46: Subtask get_pictures
[2022-06-20 01:34:25,143] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-17T00:00:00+00:00 [running]> on host b8db81cc5447
[2022-06-20 01:34:25,193] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-17T00:00:00+00:00
[2022-06-20 01:34:25,196] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data-pipline-book/2_1_download_rocket_launches.py", line 40, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:34:25,206] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220617T000000, start_date=20220620T013425, end_date=20220620T013425
[2022-06-20 01:34:25,215] {standard_task_runner.py:97} ERROR - Failed to execute job 46 for task get_pictures ('results'; 241)
[2022-06-20 01:34:25,229] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:34:25,285] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-20 01:51:14,770] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-17T00:00:00+00:00 [queued]>
[2022-06-20 01:51:14,785] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-17T00:00:00+00:00 [queued]>
[2022-06-20 01:51:14,787] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:14,790] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:51:14,792] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:14,814] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-17 00:00:00+00:00
[2022-06-20 01:51:14,822] {standard_task_runner.py:52} INFO - Started process 203 to run task
[2022-06-20 01:51:14,843] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-17T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/chapter02/dags/download_rocket_launches.py', '--cfg-path', '/tmp/tmp7_tnre_w', '--error-file', '/tmp/tmpj4di1kfh']
[2022-06-20 01:51:14,847] {standard_task_runner.py:80} INFO - Job 28: Subtask get_pictures
[2022-06-20 01:51:14,913] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-17T00:00:00+00:00 [running]> on host b39ea3d1be4a
[2022-06-20 01:51:14,992] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-17T00:00:00+00:00
[2022-06-20 01:51:14,994] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/chapter02/dags/download_rocket_launches.py", line 32, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:51:15,006] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220617T000000, start_date=20220620T015114, end_date=20220620T015115
[2022-06-20 01:51:15,021] {standard_task_runner.py:97} ERROR - Failed to execute job 28 for task get_pictures ('results'; 203)
[2022-06-20 01:51:15,054] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:51:15,088] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
