[2022-06-20 01:55:17,183] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 02_daily_schedule.fetch_events scheduled__2019-01-05T00:00:00+00:00 [queued]>
[2022-06-20 01:55:17,197] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 02_daily_schedule.fetch_events scheduled__2019-01-05T00:00:00+00:00 [queued]>
[2022-06-20 01:55:17,198] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:55:17,200] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:55:17,201] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:55:17,213] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_events> on 2019-01-05 00:00:00+00:00
[2022-06-20 01:55:17,219] {standard_task_runner.py:52} INFO - Started process 458 to run task
[2022-06-20 01:55:17,223] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '02_daily_schedule', 'fetch_events', 'scheduled__2019-01-05T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/chapter03/dags/02_daily_schedule.py', '--cfg-path', '/tmp/tmp2l8qy6dd', '--error-file', '/tmp/tmpiwuj_2bp']
[2022-06-20 01:55:17,226] {standard_task_runner.py:80} INFO - Job 39: Subtask fetch_events
[2022-06-20 01:55:17,283] {task_command.py:369} INFO - Running <TaskInstance: 02_daily_schedule.fetch_events scheduled__2019-01-05T00:00:00+00:00 [running]> on host b39ea3d1be4a
[2022-06-20 01:55:17,347] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=02_daily_schedule
AIRFLOW_CTX_TASK_ID=fetch_events
AIRFLOW_CTX_EXECUTION_DATE=2019-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-05T00:00:00+00:00
[2022-06-20 01:55:17,356] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-20 01:55:17,363] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p /data/events && curl -o /data/events.json http://events_api:5000/events']
[2022-06-20 01:55:17,398] {subprocess.py:85} INFO - Output:
[2022-06-20 01:55:17,401] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/data’: Permission denied
[2022-06-20 01:55:17,403] {subprocess.py:96} INFO - Command exited with return code 1
[2022-06-20 01:55:17,418] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-20 01:55:17,424] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=02_daily_schedule, task_id=fetch_events, execution_date=20190105T000000, start_date=20220620T015517, end_date=20220620T015517
[2022-06-20 01:55:17,441] {standard_task_runner.py:97} ERROR - Failed to execute job 39 for task fetch_events (Bash command failed. The command returned a non-zero exit code 1.; 458)
[2022-06-20 01:55:17,483] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:55:17,521] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
