[2022-06-20 01:34:20,898] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-06T00:00:00+00:00 [queued]>
[2022-06-20 01:34:20,919] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-06T00:00:00+00:00 [queued]>
[2022-06-20 01:34:20,925] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:20,931] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:34:20,937] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:20,964] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-06 00:00:00+00:00
[2022-06-20 01:34:20,977] {standard_task_runner.py:52} INFO - Started process 188 to run task
[2022-06-20 01:34:20,982] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-06T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/data-pipline-book/2_1_download_rocket_launches.py', '--cfg-path', '/tmp/tmptwofxpf6', '--error-file', '/tmp/tmp2n29g15k']
[2022-06-20 01:34:20,986] {standard_task_runner.py:80} INFO - Job 27: Subtask get_pictures
[2022-06-20 01:34:21,045] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-06T00:00:00+00:00 [running]> on host b8db81cc5447
[2022-06-20 01:34:21,132] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-06T00:00:00+00:00
[2022-06-20 01:34:21,137] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data-pipline-book/2_1_download_rocket_launches.py", line 40, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:34:21,155] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220606T000000, start_date=20220620T013420, end_date=20220620T013421
[2022-06-20 01:34:21,189] {standard_task_runner.py:97} ERROR - Failed to execute job 27 for task get_pictures ('results'; 188)
[2022-06-20 01:34:21,240] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:34:21,315] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-20 01:51:11,657] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-06T00:00:00+00:00 [queued]>
[2022-06-20 01:51:11,672] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-06T00:00:00+00:00 [queued]>
[2022-06-20 01:51:11,673] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:11,676] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:51:11,678] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:11,714] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-06 00:00:00+00:00
[2022-06-20 01:51:11,722] {standard_task_runner.py:52} INFO - Started process 169 to run task
[2022-06-20 01:51:11,726] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-06T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/chapter02/dags/download_rocket_launches.py', '--cfg-path', '/tmp/tmptaomujjr', '--error-file', '/tmp/tmpruwrooum']
[2022-06-20 01:51:11,728] {standard_task_runner.py:80} INFO - Job 17: Subtask get_pictures
[2022-06-20 01:51:11,842] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-06T00:00:00+00:00 [running]> on host b39ea3d1be4a
[2022-06-20 01:51:11,915] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-06T00:00:00+00:00
[2022-06-20 01:51:11,921] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/chapter02/dags/download_rocket_launches.py", line 32, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:51:11,932] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220606T000000, start_date=20220620T015111, end_date=20220620T015111
[2022-06-20 01:51:11,943] {standard_task_runner.py:97} ERROR - Failed to execute job 17 for task get_pictures ('results'; 169)
[2022-06-20 01:51:11,986] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:51:12,022] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
