[2022-06-20 01:34:22,574] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-08T00:00:00+00:00 [queued]>
[2022-06-20 01:34:22,588] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-08T00:00:00+00:00 [queued]>
[2022-06-20 01:34:22,590] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:22,593] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:34:22,595] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:34:22,625] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-08 00:00:00+00:00
[2022-06-20 01:34:22,648] {standard_task_runner.py:52} INFO - Started process 225 to run task
[2022-06-20 01:34:22,653] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-08T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/data-pipline-book/2_1_download_rocket_launches.py', '--cfg-path', '/tmp/tmp6m7qbz2t', '--error-file', '/tmp/tmpyb8i9okg']
[2022-06-20 01:34:22,656] {standard_task_runner.py:80} INFO - Job 39: Subtask get_pictures
[2022-06-20 01:34:22,783] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-08T00:00:00+00:00 [running]> on host b8db81cc5447
[2022-06-20 01:34:23,021] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-08T00:00:00+00:00
[2022-06-20 01:34:23,026] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data-pipline-book/2_1_download_rocket_launches.py", line 40, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:34:23,055] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220608T000000, start_date=20220620T013422, end_date=20220620T013423
[2022-06-20 01:34:23,078] {standard_task_runner.py:97} ERROR - Failed to execute job 39 for task get_pictures ('results'; 225)
[2022-06-20 01:34:23,121] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:34:23,236] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-20 01:51:11,983] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-08T00:00:00+00:00 [queued]>
[2022-06-20 01:51:11,996] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-08T00:00:00+00:00 [queued]>
[2022-06-20 01:51:11,998] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:11,999] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 01:51:12,001] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 01:51:12,016] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_pictures> on 2022-06-08 00:00:00+00:00
[2022-06-20 01:51:12,022] {standard_task_runner.py:52} INFO - Started process 174 to run task
[2022-06-20 01:51:12,024] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'scheduled__2022-06-08T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/chapter02/dags/download_rocket_launches.py', '--cfg-path', '/tmp/tmpeea04mna', '--error-file', '/tmp/tmpepo3vu4g']
[2022-06-20 01:51:12,026] {standard_task_runner.py:80} INFO - Job 19: Subtask get_pictures
[2022-06-20 01:51:12,113] {task_command.py:369} INFO - Running <TaskInstance: download_rocket_launches.get_pictures scheduled__2022-06-08T00:00:00+00:00 [running]> on host b39ea3d1be4a
[2022-06-20 01:51:12,364] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2022-06-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-08T00:00:00+00:00
[2022-06-20 01:51:12,368] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/chapter02/dags/download_rocket_launches.py", line 32, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2022-06-20 01:51:12,390] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20220608T000000, start_date=20220620T015111, end_date=20220620T015112
[2022-06-20 01:51:12,412] {standard_task_runner.py:97} ERROR - Failed to execute job 19 for task get_pictures ('results'; 174)
[2022-06-20 01:51:12,449] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-20 01:51:12,482] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
